### ISSUE TITLE
Update featured image code

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/rru-website#1]
Not actually adding instructions because we discussed them, but just creating this issue so we have a place to discuss.

**Comment by tvroylandt** [comment]
Done here : https://github.com/rfortherestofus/rru-website/commit/7f8efae800beddb60a7034928c8c9e8124c77405

Some cases are not really well handled like `sf` (because it's a .gif) or some icons that are too narrow.

**Comment by dgkeyes** [comment]
You're the man!

**Comment by dgkeyes** [comment]
Also, in terms of tracking time for things like this, please just put it in the General project on Toggl. Thanks!

**Comment by dgkeyes** [comment]
I'm having issues with this for the resources that don't have a logo (in other words, the ones that require you to take a screenshot of the webpage). It does the first one, but then throws this error. Any idea what I might do to fix it?

https://evamaerey.github.io/little_flipbooks_library/data_cleaning/data_cleaning#1 screenshot completed
convert: unable to open image '/Users/davidkeyes/Documents/Work/R': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'for': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'for': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'the': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'the': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'Rest': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'Rest': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'of': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'of': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'Us/projects/rru-website/plots/data-cleaning-flipbook.png': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'Us/projects/rru-website/plots/data-cleaning-flipbook.png': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'for': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'for': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'the': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'the': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'Rest': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'Rest': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: unable to open image 'of': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: unable to open image 'of': No such file or directory @ error/blob.c/OpenBlob/3537.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/572.
convert: no images defined `Us/projects/rru-website/plots/data-cleaning-flipbook.png' @ error/convert.c/ConvertImageCommand/3304.
 Error in (function (filename, geometry)  : 
  Resizing with `gm convert`, `magick convert` or `convert` failed.

**Comment by dgkeyes** [comment]
Oh wait, I think this is working now! Not sure why, but no need to work on it further.
